# Generated by Django 5.2.8 on 2025-11-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rib',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
