# Generated by Django 5.2.9 on 2025-12-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_user_solde_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rib',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solde',
        ),
    ]
