# Generated by Django 5.2.9 on 2025-12-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rib',
            field=models.CharField(blank=True, max_length=34, unique=True),
        ),
    ]
