# Generated by Django 5.2.9 on 2025-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0002_alter_account_rib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='DT', max_length=5),
        ),
    ]
